---
- hosts: beaker
  tasks:
    - fail:
        msg: |
          Please rename {{ item }} to beaker_{{ item }} in group_vars/all.
      when: "hostvars['beaker'][item] is defined"
      with_items:
        - admin_login
        - admin_password
        - admin_email
        - admin_fullname
        - lab
        - db

    - import_role:
        name: openstack.redhat-subscription
      vars:
        rhsm_repos:
          - rhel-7-server-rpms
          - rhel-7-server-extras-rpms
          - rhel-7-server-optional-rpms
      when: ansible_distribution == 'RedHat'
      become: true

    - import_role:
        name: redhat-cip.beaker
